### ISSUE TITLE
CEM: Remove isFinal 

### ISSUE THREAD

**Issue by omelkonian** [omelkonian/formal-utxo#16]
As discussed with others, we should just omit any notion of finality to make our lives simpler.
This will allows us to remove the special cases for final states in completeness/soundness.

In the ISoLa paper, mention:
1. Milner's quote about ineracting systems (essestially every state is final) 
2. the optimization implemented in Cardano (where we do not pollute the UTXO-set with 'final' states)

**Comment by jmchapman** [comment]
done - https://github.com/omelkonian/formal-utxo/commit/3e956ba072a8f9256eaf76d0bf20d0fe85a4948c
